version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pet-health-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
    env_file:
      - ./backend/.env.production
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - pet-health-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pet-health-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - pet-health-network

  nginx:
    image: nginx:alpine
    container_name: pet-health-nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - pet-health-network

networks:
  pet-health-network:
    driver: bridge

volumes:
  uploads:
  logs:
